-- -- Creating table 'Fakultetas'
-- CREATE TABLE faculty (
--     id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     faculty_name VARCHAR2(100)
-- );

-- -- Creating table 'Studentas'
-- CREATE TABLE student (
--     id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     first_name VARCHAR2(100),
--     last_name VARCHAR2(100),
--     address VARCHAR2(200),
--     semester number,
--     faculty_id number,
--     FOREIGN KEY (faculty_id) REFERENCES faculty(id)
-- );

-- -- Creating table 'Destytojas'
-- CREATE TABLE lecturer (
--     id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     first_name VARCHAR2(100),
--     last_name VARCHAR2(100),
--     faculty_id number,
--     FOREIGN KEY (faculty_id) REFERENCES faculty(id)
-- );

-- -- Creating table 'Destomas_dalykas'
-- CREATE TABLE subject (
--     id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     lecturer_id number,
--     name VARCHAR2(100),
--     description VARCHAR2(500),
--     semester number,
--     FOREIGN KEY (lecturer_id) REFERENCES lecturer(id)
-- );

-- -- Creating table 'Pasirinktas_dalykas'
-- CREATE TABLE choosen_subject (
--     id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     subject_id number,
--     student_id number,
--     created_at date,
--     FOREIGN KEY (subject_id) REFERENCES subject(id),
--     FOREIGN KEY (student_id) REFERENCES student(id)
-- );

-- Lentele is punkto B
CREATE TABLE invalid_records (
    id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id number,
    subject_id number,
    reason VARCHAR2(200),
    created_at date DEFAULT sysdate
);